POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "Toyota",
    "model": "Camry",
    "year": 2012,
    "mileage": 12345,
    "lng": 0,
    "lat": 0,
    "price": 500000
}

### Approve an existing report

PATCH http://localhost:3000/reports/5
Content-Type: application/json

{
    "approved": false
}