### Create a new User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"yookidz1@gmail.com",
    "password": "qwer1234"
}

### Get the currently signed in user
GET http://localhost:3000/auth/whoami

### Sign out
POST http://localhost:3000/auth/signout

### Sign In as an existing user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email":"yookidz@gmail.com",
    "password": "qwer1234"
}

### Find a particular user with a given ID
GET http://localhost:3000/auth/2

### Find all users with a given email
GET http://localhost:3000/auth

### Delete a user given id
DELETE http://localhost:3000/auth/4

### Update a user
PATCH http://localhost:3000/auth/4
Content-Type: application/json

{
    "email": "bbb@aaaa.com"
}

### Set a color
GET http://localhost:3000/auth/colors/blue

### Get the color
GET http://localhost:3000/auth/colors